//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public System.Guid ApplicationUserId { get; set; }
        public string DomainCredential { get; set; }
        public string MachineAddress { get; set; }
        public string Name { get; set; }
        public System.DateTime LastAccessDateTime { get; set; }
        public int Version { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.Guid EditedById { get; set; }
        public System.DateTime EditedDateTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
